### ISSUE TITLE
Currency Switch from $ to € not reflecting in product detail page

### ISSUE THREAD

**Issue by Ishak-ali** [Simicart/siminia-public#100]
When user switch site currency from $ to € then it should reflect in all places, its working fine in all places except product detail page
Please refer to below image
![image](https://user-images.githubusercontent.com/34087502/154831193-a8ccd362-95c4-4c17-abd7-3fdb91eccd0b.png)

so please take a look and fix this issue

**Comment by alitonia** [comment]
@Ishak-ali  can you give me the steps to reproduce this error, the price switching still works on my environment.

**Comment by codynguyen1** [comment]
Hi @Ishak-ali , the problem is related to our varnish configuration, I have resolved it from server with no change on client, if you are deploying this repo on your website, you won't need to worry about this issue.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/16347586/158732450-3c16d37a-671f-4974-9e94-ceba9753fbd0.png">
