### ISSUE TITLE
Title and icons for "index.html" in dist folder should be taken from Magento ** minor 

### ISSUE THREAD

**Issue by Watch3ruk** [Simicart/siminia-public#38]
Title and icons for `"index.html`" in dist folder should be taken from Magento config , 

currently they are hardcoded and pre-filed with simi values. \

🐞 Report

yarn run build 
share the link - it will have icon and title of simi 
should have title and icon set in Magento .

**Comment by MaxTa91** [comment]
@Watch3ruk Yes, they are the fixed value because it is our theme :) we want to make SimiCart's branding. 
However, They will be replaced when your PWA is loaded. 
Regarding shared link, PWA studio isn't supported SSR so I think you use rendertron or prerender.io In order to get the correct content instead of using the fixed value at index.html. 
Moreover, You can change them to your brand if you need :).

**Comment by Watch3ruk** [comment]
hi , changing values in index html actually changes the link . 
To reproduce - use WhatsApp or any other messaging platform put in you site address , change values of tittle in index html and see how it renders .

**Comment by MaxTa91** [comment]
@Watch3ruk I just tried to share via Facebook. Please see the screenshot
![Screen Shot 2022-01-14 at 09 52 25](https://user-images.githubusercontent.com/11706605/149443498-e44dffe9-6639-489a-839e-2787efb13a41.png)

Your title was updated correctly but some images aren't changed as Favicon. Please update them.
